### PR TITLE
use kind's other kubeconfig fields if none are set in the existing co…

### LINKED ISSUE #1242: kubeconfig file created by Kind is missing `apiVersion` and `kind`
**What happened**:

In recent versions, Kind automatically populates ~/.kube/config

However, if ~/.kube/config is missing or empty, Kind doesn't populate it correctly.

It's does not include `apiVersion` and `kind`.

**What you expected to happen**:

If Kind is going to automatically mess with kube config, it needs to set it correctly.

Kubernetes client libraries, such as the official Javascript library, will fail if they cannot find these fields.

**How to reproduce it (as minimally and precisely as possible)**:

1. Start with an empty kubeconfig file
2. Run `kind create`
3. Look at ~/kube/.config

**Anything else we need to know?**:

Kubernetes client library failing as a result:

TypeError: unknown version: undefined
    at KubeConfig.loadFromString (node_modules/@kubernetes/client-node/dist/config.js:100:19)

**Environment:**
kind v0.6.1 go1.13.4 darwin/amd64

- kind version: (use `kind version`): v0.6.1
- Kubernetes version: (use `kubectl version`): 

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"211047e9a1922595eaa3a1127ed365e9299a6c23", GitTreeState:"clean", BuildDate:"2019-10-15T12:11:03Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-20T19:26:38Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

- Docker version: (use `docker info`):

Server Version: 19.03.5
 Kernel Version: 4.9.184-linuxkit

- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by BenTheElder**
…nfig

fixes #1242

### CODE REVIEW

File: pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge.go [hunk 1]
```diff
@@ -98,5 +98,14 @@ func merge(existing, kind *Config) error {
 	// set the current context
 	existing.CurrentContext = kind.CurrentContext
 
+	// TODO: We should not need this, but it allows broken clients that depend
+	// on apiVersion and kind to work. Notably the upstream javascript client.
+	// See: https://github.com/kubernetes-sigs/kind/issues/1242
+	if len(existing.OtherFields) == 0 {
```
Comment (BenTheElder) [inline pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge.go]: We might need a future enhancement specifically to default `"kind"` and `"apiVersion"` but this is simpler, and solves the immediate concern (when empty or otherwise unset existing files lack any of these fields).

Comment (BenTheElder) [reply pkg/cluster/internal/kubeconfig/internal/kubeconfig/merge.go]: it also doesn't involve any magical constants.
