### PR TITLE
Fix pipe closing race in kind export logs

### LINKED ISSUE #999: periodic errors exporting logs
we're seeing errors tarring up log files for exporting the logs
/assign 
/priority important-soon
/lifecycle active

xref previously: https://github.com/kubernetes-sigs/kind/issues/949

### PR DESCRIPTION
**Pull request by amwat**
fixes #999 

Since the reader/writer are running as separate processes, closing either prematurely will result in a broken pipe until we ensure both processes have finished.

Simplified the logic to close the pipe on defer once we've aggregated both the errors.

Also reverted the rsync logic since that was a red herring workaround (and was also doubling the time).

### CODE REVIEW

**Comment by amwat** [comment]
Verified by running kind export logs around 500 times without failure.

**Comment by BenTheElder** [comment]
```
pkg/internal/cluster/logs/logs.go:141:6: `mktemp` is unused (deadcode)
func mktemp(node nodes.Node) (string, error) {
     ^
```

let's delete that.

File: pkg/internal/cluster/logs/logs.go [hunk 1]
```diff
@@ -114,24 +116,18 @@ func Collect(logger log.Logger, nodes []nodes.Node, dir string) error {
...
+	cmd := node.Command(
+		"sh", "-c",
+		// Tar will exit 1 if a file changed during the archival.
+		// We don't care about this, so we're invoking it in a shell
+		// And masking out 1 as a return value.
+		// Fatal errors will return exit code 2.
+		// http://man7.org/linux/man-pages/man1/tar.1.html#RETURN_VALUE
+		fmt.Sprintf(
+			`tar --hard-dereference -C %s -chf - . || (r=$?; [ $r -eq 1 ] || exit $r)`,
+			shellescape.Quote(path.Clean(nodeDir)+"/")),
```
Comment (BenTheElder) [inline pkg/internal/cluster/logs/logs.go]: nit city: normally would balance the closing paren to it's own line, but gofmt seems ok with this

Comment (amwat) [reply pkg/internal/cluster/logs/logs.go]: done

File: pkg/internal/cluster/logs/logs.go [hunk 2]
```diff
@@ -18,12 +18,13 @@ package logs
...
 import (
 	"archive/tar"
+	"fmt"
 	"io"
 	"os"
 	"path"
 	"path/filepath"
-	"strings"
 
+	"github.com/alessio/shellescape"
```
Comment (BenTheElder) [inline pkg/internal/cluster/logs/logs.go]: nit: grouping should be:
```
stdlib # go standard library

github.com # third party

k8s.io/ # kubernetes project packages, almost "our" code
sigs.k8s.io/

sigs.k8s.io/kind # our public packages

sigs.k8s.io/kind/pkg/internal/... # internal
```

with blanks in between.

**Comment by BenTheElder** [comment]
Thanks! This was fun to debug 😛

**Comment by aojea** [comment]
Finally , awesome :)
