### PR TITLE
set skipPhases in Init and JoinConfiguration

### LINKED ISSUE #3606: Unable to skipPhases: addons/coredns
**What happened**:

When trying to install `kind` cluster with coredns disabled using `skipPhases`, the `skipPhases` are not honored. From the verbose log I attached you can see that `skipPhases` were added to InitConfiguration using `kubeadmConfigPatches` I used in my config (see how to reproduce).

Attached Log: [kind-test.log](https://github.com/kubernetes-sigs/kind/files/15292297/kind-test.log)

The result is this:

```bash
$ kubectl get pods -A
NAMESPACE            NAME                                                   READY   STATUS    RESTARTS   AGE
kube-system          coredns-76f75df574-g4xnp                               0/1     Pending   0          92s
kube-system          coredns-76f75df574-kd54l                               0/1     Pending   0          92s
kube-system          etcd-my-dev-cluster-control-plane                      1/1     Running   0          108s
kube-system          kube-apiserver-my-dev-cluster-control-plane            1/1     Running   0          106s
kube-system          kube-controller-manager-my-dev-cluster-control-plane   1/1     Running   0          108s
kube-system          kube-proxy-2gwdt                                       1/1     Running   0          92s
kube-system          kube-scheduler-my-dev-cluster-control-plane            1/1     Running   0          106s
local-path-storage   local-path-provisioner-7577fdbbfb-ct4ff                0/1     Pending   0          92s
```

**What you expected to happen**:

CoreDNS will not be installed.

**How to reproduce it (as _minimally_ and precisely as possible)**:

Create cluster with following configuration:

```yaml
---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  disableDefaultCNI: true
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    skipPhases:
    - addon/coredns
```

For example `kind create cluster --name my-dev-cluster --config=kind-test.yaml -v9`.

**Anything else we need to know?**:

Probably it is overriden here - https://github.com/kubernetes-sigs/kind/blob/v0.22.0/pkg/cluster/internal/create/actions/kubeadminit/init.go#L63-L80

**Environment:**

- kind version: (use `kind version`): kind v0.22.0 go1.20.13 linux/amd64
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`): Server Version: 20.10.22
- OS (e.g. from `/etc/os-release`): Fedora 35
- Kubernetes version: (use `kubectl version`): 
```bash
- $ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```
- Any proxies or other special environment settings?: No

### PR DESCRIPTION
**Pull request by nojnhuh**
Fixes #3606.

This PR moves the `--skip-phases` flag from the `kubeadm init` and `kubeadm join` commands to the config file for recent versions of Kubernetes to allow users to patch them from a Cluster config. Older (< 1.23) versions of Kubernetes will still specify the `--skip-phases` flag for those commands for compatibility.

### CODE REVIEW

File: pkg/cluster/internal/create/actions/kubeadmjoin/join.go [hunk 1]
```diff
@@ -117,18 +118,31 @@ func joinWorkers(
 
 // runKubeadmJoin executes kubeadm join command
 func runKubeadmJoin(logger log.Logger, node nodes.Node) error {
-	// run kubeadm join
-	// TODO(bentheelder): this should be using the config file
```
Comment (nojnhuh) [inline pkg/cluster/internal/create/actions/kubeadmjoin/join.go:121]: @BenTheElder It seemed like this was the last missing piece for this TODO. Please let me know if there's still a gap here where this comment is still valuable.

File: pkg/cluster/internal/kubeadm/config.go [hunk 2]
```diff
@@ -107,6 +107,10 @@ type DerivedConfigData struct {
 	IPv6 bool
 	// kubelet cgroup driver, based on kubernetes version
 	CgroupDriver string
+	// JoinSkipPhases are the skipPhases values for the JoinConfiguration.
+	JoinSkipPhases []string
+	// InitSkipPhases are the skipPhases values for the InitConfiguration.
+	InitSkipPhases []string
```
Comment (neolit123) [inline pkg/cluster/internal/kubeadm/config.go:113]: was this discussed on the ticket?
kind doesn't have to wrap these kubeadm options, and users can pass a custom slice via kind kubeadm config patches, which would override the default to skip the preflight.

Comment (nojnhuh) [reply pkg/cluster/internal/kubeadm/config.go:113]: Not sure we got this deep into detail in the issue beyond setting `skipPhases` in the config (https://github.com/kubernetes-sigs/kind/issues/3606#issuecomment-2123157692), but I can see where we could get rid of these fields by hardcoding `preflight` and conditionally adding `addon/kube-proxy` right in the template. Is that what you mean? Or are you suggesting not to specify any `skipPhases` by default? Overall I was trying to preserve the existing default behavior since I don't fully understand the implications of running the preflight checks here.

Comment (neolit123) [reply pkg/cluster/internal/kubeadm/config.go:113]: NVM, i mistakenly thought that this exposes the skip phase slices in the public facing kind config, which is not the case.

Comment (BenTheElder) [reply pkg/cluster/internal/kubeadm/config.go:113]: yeah, naming is hard and all that, this is internal / plumbing options to the config templates

File: pkg/cluster/internal/create/actions/kubeadmjoin/join.go (hunk 1 above)
Comment (BenTheElder) [reply pkg/cluster/internal/create/actions/kubeadmjoin/join.go:121]: yep! thanks for fixing my ancient TODO 😅

File: pkg/cluster/internal/kubeadm/config.go [hunk 3]
```diff
@@ -166,6 +170,14 @@ func (c *ConfigData) Derive() {
 		runtimeConfig = append(runtimeConfig, fmt.Sprintf("%s=%s", k, v))
 	}
 	c.RuntimeConfigString = strings.Join(runtimeConfig, ",")
+
+	// skip preflight checks, as these have undesirable side effects
```
[the remark this answers is not in the document]
Comment (BenTheElder) [reply pkg/cluster/internal/kubeadm/config.go:174]: (also the 1.13+ comment is now redundant, we stopped supporting Kubernetes < 1.15 in https://github.com/kubernetes-sigs/kind/releases/tag/v0.16.0)

**Review by BenTheElder — COMMENTED** [review]
/lgtm
/approve
thank you!

we can rewrite those old comments in a follow-up
