### PR TITLE
Block `docker exec` until systemd in the node container initializes /sys/fs/cgroup (Fix docker+cgroup2+rootless CI failure)

### LINKED ISSUE #2409: CI failing for cgroup2+docker+rootless
CI is recently failing for cgroup2+docker+rootless.

CI isn't failing for cgroup2+docker+rootful and cgroup2+podman+rootless.

Also the failure is not reproducible on my local Vagrant.

https://github.com/kubernetes-sigs/kind/runs/3255789909

`kind-logs-cgroup2-docker-rootless-1102670304.zip:kind-control-plane/kubelet.log`

```
-- Journal begins at Thu 2021-08-05 19:38:30 UTC, ends at Thu 2021-08-05 19:40:32 UTC. --
Aug 05 19:38:31 kind-control-plane systemd[1]: Condition check resulted in kubelet: The Kubernetes Node Agent being skipped.
Aug 05 19:38:36 kind-control-plane systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Aug 05 19:38:36 kind-control-plane sh[217]: ERROR: this script needs /sys/fs/cgroup/cgroup.procs to be empty (for writing the top-level cgroup.subtree_control)
Aug 05 19:38:36 kind-control-plane systemd[1]: kubelet.service: Control process exited, code=exited, status=1/FAILURE
Aug 05 19:38:36 kind-control-plane systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 05 19:38:36 kind-control-plane systemd[1]: Failed to start kubelet: The Kubernetes Node Agent.
Aug 05 19:38:37 kind-control-plane systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 1.
Aug 05 19:38:37 kind-control-plane systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 05 19:38:37 kind-control-plane systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Aug 05 19:38:37 kind-control-plane sh[220]: ERROR: this script needs /sys/fs/cgroup/cgroup.procs to be empty (for writing the top-level cgroup.subtree_control)
Aug 05 19:38:37 kind-control-plane systemd[1]: kubelet.service: Control process exited, code=exited, status=1/FAILURE
Aug 05 19:38:37 kind-control-plane systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 05 19:38:37 kind-control-plane systemd[1]: Failed to start kubelet: The Kubernetes Node Agent.
...
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Wait until systemd initializes the cgroup hier so that `docker exec` can be executed safely without breaking cgroup v2 hierarchy.

This is implemented by grepping `docker logs` with "Reached target .*Multi-User System.*" message from systemd.
(we can't use `docker exec` to check whether we are allowed to run `docker exec`, obviously.)

Needed for avoiding `ERROR: this script needs /sys/fs/cgroup/cgroup.procs to be empty (for writing the top-level cgroup.subtree_control)`

Fix  #2409
Replace #2410

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
@aojea @BenTheElder PTAL

**Comment by aojea** [comment]
> Wait until systemd initializes the cgroup hier so that docker exec can be executed safely without breaking cgroup v2 hierarchy.

is one specific `docker exec` who breaks the cgroup? os is the entrypoint script or one of the systemd units?

i.e, if this is because of the `create-kubelet-cgroup-v2`script we can just delay it with something like
```
diff --git a/images/base/files/etc/systemd/system/kubelet.service.d/10-kubeadm.conf b/images/base/files/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
index 04fd9853..804b7850 100644
--- a/images/base/files/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
+++ b/images/base/files/etc/systemd/system/kubelet.service.d/10-kubeadm.conf
@@ -13,3 +13,6 @@ EnvironmentFile=-/etc/default/kubelet
 ExecStartPre=/bin/sh -euc "if [ -f /sys/fs/cgroup/cgroup.controllers ]; then create-kubelet-cgroup-v2; fi"
 ExecStart=
 ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_CONFIG_ARGS $KUBELET_KUBEADM_ARGS $KUBELET_EXTRA_ARGS --cgroup-root=/kubelet
+[Install]
+Requires=multi-user.target
```

**Comment by AkihiroSuda** [comment]
I don't think delaying `create-kubelet-cgroup-v2` make sense.
The problem is that running `docker exec` before systemd initializes cgroups breaks cgroups hier.

**Comment by AkihiroSuda** [comment]
@BenTheElder Could you take a look

File: pkg/cluster/internal/providers/common/provision.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+	fullArgs := append([]string{"run", "--name", name}, args...)
+	if err := exec.Command(engine, fullArgs...).Run(); err != nil {
+		return fmt.Errorf("%s run error: %w", engine, err)
+	}
+
+	if o.waitUntilLogRegexpMatches != nil {
+		logCtx := context.Background()
+		logCtx, logCancel := context.WithTimeout(logCtx, 30*time.Second)
+		defer logCancel()
+		// use os/exec.CommandContext directly, as kind/pkg/exec.CommandContext lacks support for killing
```
Comment (BenTheElder) [inline pkg/cluster/internal/providers/common/provision.go:83]: IMO this should be fixed instead in the future. The abstraction exists for purposes such as testing and composition with running commands in nested environments.

Comment (BenTheElder) [reply pkg/cluster/internal/providers/common/provision.go:83]: It's also not clear that we need to kill processes directly at all? We should be able to kill indirectly by telling docker/podman to delete the container, which is what the rest of the tool relies on.

**Review by BenTheElder — APPROVED** [review]
For a bugfix like this I would prefer to unblock and @aojea you can approve at your own discretion.

I'm available today doing some catchup but I will once again be out with an ongoing family matter ..

I don't think this is implemented quite ideally but given that it's internal implementation details we can always alter that in a future PR. If it were adding a new user facing feature I might try to be more immediately involved up-front.
