### PR TITLE
fix `kind get clusters` via nerdctl

### LINKED ISSUE #3813: Listing clusters with nerdctl raises errors
**What happened**:

```console
> ./kind version  
kind v0.26.0-alpha go1.23.3 linux/amd64
> nerdctl --version
nerdctl version 2.0.1
> ./kind get clusters 
ERROR: failed to list clusters: command "nerdctl ps -a --filter label=io.x-k8s.kind.cluster --format '{{index .Labels "io.x-k8s.kind.cluster"}}'" failed with error: exit status 1
Command Output: time="2024-12-09T18:01:03+09:00" level=fatal msg="template: :1:2: executing \"\" at <index .Labels \"io.x-k8s.kind.cluster\">: error calling index: cannot index slice/array with type string"
```

Also happened in [`delete clusters --all`](https://github.com/kubernetes-sigs/kind/blob/8759112b9f3f1d2e3e46f454339f25b2befda4be/pkg/cmd/kind/delete/clusters/deleteclusters.go#L75-L80) and it does not delete clusters

```console
> kind delete clusters --all 
^[[AERROR: failed listing clusters for delete: failed to list clusters: command "nerdctl ps -a --filter label=io.x-k8s.kind.cluster --format '{{index .Labels "io.x-k8s.kind.cluster"}}'" failed with error: exit status 1
Command Output: time="2024-12-10T11:43:50+09:00" level=fatal msg="template: :1:2: executing \"\" at <index .Labels \"io.x-k8s.kind.cluster\">: error calling index: cannot index slice/array with type string"
> kind delete cluster        
Deleting cluster "kind" ...
Deleted nodes: ["kind-control-plane"]
```

**What you expected to happen**:

It returns cluster names without any error

**How to reproduce it (as _minimally_ and precisely as possible)**:

1. Use latest kind and nerdctl
2. `kind create cluster`
3. `kind get clusters `

**Anything else we need to know?**:

**Environment:**

- kind version: (use `kind version`): `kind v0.25.0 go1.23.3 linux/amd64`, `kind v0.26.0-alpha go1.23.3 linux/amd64`
- Runtime info: (use `docker info`, `podman info` or `nerdctl info`):

```console
> nerdctl info
Client:
 Namespace:	default
 Debug Mode:	false

Server:
 Server Version: v2.0.0
 Storage Driver: overlayfs
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Log:     fluentd journald json-file none syslog
  Storage: native overlayfs stargz fuse-overlayfs
 Security Options:
  apparmor
  seccomp
   Profile: builtin
  cgroupns
  rootless
 Kernel Version:   6.11.0-9-generic
 Operating System: Ubuntu 24.10
 OSType:           linux
 Architecture:     x86_64
 CPUs:             4
 Total Memory:     3.817GiB
 Name:             lima-default
 ID:               178c32f0-2f3a-4cf1-aecb-b456e22539e6

WARNING: AppArmor profile "nerdctl-default" is not loaded.
         Use 'sudo nerdctl apparmor load' if you prefer to use AppArmor with rootless mode.
         This warning is negligible if you do not intend to use AppArmor.
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- OS (e.g. from `/etc/os-release`):

```console
> cat /etc/os-release
PRETTY_NAME="Ubuntu 24.10"
NAME="Ubuntu"
VERSION_ID="24.10"
VERSION="24.10 (Oracular Oriole)"
VERSION_CODENAME=oracular
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=oracular
LOGO=ubuntu-logo
```

- Kubernetes version: (use `kubectl version`):

```console
> kubectl version
Client Version: v1.31.2
Kustomize Version: v5.4.2
Server Version: v1.31.2
```

- Any proxies or other special environment settings?: Tested on lima instance

### PR DESCRIPTION
**Pull request by kachick**
Fixes #3813

nerdctl fixed the `.Label` behavior in v1.7.0.
https://github.com/containerd/nerdctl/pull/2619

However `index .Labels` syntax is not yet supported at least in v2.0.1.
(The style is also used for podman provider, and it is available)
    
This PR aims to follow up https://github.com/kubernetes-sigs/kind/pull/3429

### CODE REVIEW

**Comment by aojea** [comment]
/ok-to-test

@AkihiroSuda can you ping some nerdctl maintainers to check if this is correct?

File: pkg/cluster/internal/providers/nerdctl/provider.go [hunk 1]
```diff
@@ -125,7 +125,7 @@ func (p *provider) ListClusters() ([]string, error) {
 		// filter for nodes with the cluster label
 		"--filter", "label="+clusterLabelKey,
 		// format to include the cluster name
-		"--format", fmt.Sprintf(`{{index .Labels "%s"}}`, clusterLabelKey),
+		"--format", fmt.Sprintf(`{{.Label "%s"}}`, clusterLabelKey),
```
Comment (BenTheElder) [inline pkg/cluster/internal/providers/nerdctl/provider.go:128]: Do we know if this ever worked? Do we need to version gate it? Or was it just copy-pasted from the docker provider and never worked?

Comment (AkihiroSuda) [reply pkg/cluster/internal/providers/nerdctl/provider.go:128]: Probably this was just copied without testing?

Comment (AkihiroSuda) [reply pkg/cluster/internal/providers/nerdctl/provider.go:128]: This kind of difference should be mentioned in code comment lines

**Review by AkihiroSuda — APPROVED** [review]

File: pkg/cluster/internal/providers/nerdctl/provider.go (hunk 1 above)
Comment (aojea) [reply pkg/cluster/internal/providers/nerdctl/provider.go:128]: it seems podman also already implemented this https://github.com/containers/podman/pull/20958

It is using the old format https://github.com/kubernetes-sigs/kind/blob/f3a83441a7db2ecf3432d973ef9bdcf618215065/pkg/cluster/internal/providers/podman/provider.go#L110-L111

**Comment by kachick** [comment]
Thanks for reviewing and merging 🙏

File: pkg/cluster/internal/providers/nerdctl/provider.go (hunk 1 above)
Comment (BenTheElder) [reply pkg/cluster/internal/providers/nerdctl/provider.go:128]: We should check the docker driver and probably re-align this.

**Comment by BenTheElder** [comment]
Thanks all!
