### PR TITLE
fix kind-with-registry for v0.8

### LINKED ISSUE #1541: local registry doesn't work anymore with kind v0.8.0
I'm having trouble getting Kind with a local registry to work on Kind v0.8.0. I'm using the instructions here:
https://kind.sigs.k8s.io/docs/user/local-registry/

I've tried running the registry with `--net=kind` (per the v0.8.0 release notes) and that didn't appear to help. 

Are these instructions expected to still work?

### PR DESCRIPTION
**Pull request by BenTheElder**
fixes #1541

### CODE REVIEW

File: site/static/examples/kind-with-registry.sh [hunk 1]
```diff
@@ -13,7 +13,6 @@ if [ "${running}" != 'true' ]; then
     -d --restart=always -p "${reg_port}:5000" --name "${reg_name}" \
     registry:2
 fi
-reg_ip="$(docker inspect -f '{{.NetworkSettings.IPAddress}}' "${reg_name}")"
 
 # create a cluster with the local registry enabled in containerd
 cat <<EOF | kind create cluster --name "${KIND_CLUSTER_NAME}" --config=-
```
Comment (BenTheElder) [inline site/static/examples/kind-with-registry.sh:18]: we could actually stop using the `--name` flag

File: site/static/examples/kind-with-registry.sh [hunk 2]
```diff
@@ -1,9 +1,6 @@
 #!/bin/sh
 set -o errexit
 
-# desired cluster name; default is "kind"
-KIND_CLUSTER_NAME="${KIND_CLUSTER_NAME:-kind}"
```
Comment (BenTheElder) [inline site/static/examples/kind-with-registry.sh:5]: this is handled internally to kind now.

File: site/static/examples/kind-with-registry.sh [hunk 3]
```diff
@@ -13,14 +10,21 @@ if [ "${running}" != 'true' ]; then
...
-    endpoint = ["http://${reg_ip}:${reg_port}"]
+    endpoint = ["http://${reg_name}:${reg_port}"]
 EOF
+
+# connect the registry to the cluster network
+docker network connect "kind" "${reg_name}"
+
+# tell https://tilt.dev to use the registry
+for node in $(kind get nodes); do
+  kubectl annotate node "${node}" "tilt.dev/registry=localhost:${reg_port}";
```
Comment (BenTheElder) [inline site/static/examples/kind-with-registry.sh:29]: @nicks is this documented anywhere?

Comment (nicks) [reply site/static/examples/kind-with-registry.sh:29]: nope, I'm hoping to promote a shared standard that is not tilt-specific, this is a hack to unblock people

Comment (BenTheElder) [reply site/static/examples/kind-with-registry.sh:29]: Awesome! 👍

Comment (nicks) [reply site/static/examples/kind-with-registry.sh:29]: would be equally happy with an annotation like `kind.sigs.k8s.io/registry=localhost:${reg_port}` if you're uncomfortable with the tilt.dev annotation

Comment (BenTheElder) [reply site/static/examples/kind-with-registry.sh:29]: that sounds good to me :+1: 
I'm fine with tilt.dev but it probably looks better to use a kind annotation

Comment (nicks) [reply site/static/examples/kind-with-registry.sh:29]: added some documentation
https://docs.tilt.dev/choosing_clusters.html#discovering-the-registry
that you can point people to if anyone asks

Comment (BenTheElder) [reply site/static/examples/kind-with-registry.sh:29]: i'm going to leave this for now since it already works and doesn't seem all that "offensive" in a demo script until I can think of how we want to be doing this in the future when we actually integrate something properly which is probably soonish anyhow.

Comment (BenTheElder) [reply site/static/examples/kind-with-registry.sh:29]: thanks for documenting this!

Comment (BenTheElder) [reply site/static/examples/kind-with-registry.sh]: is there somewhere we can follow the standardization effort? I think this is a really great idea

Comment (nicks) [reply site/static/examples/kind-with-registry.sh]: nope, it's been mostly off-the-cuff conversations I've been having with people. It falls at the intersection of a few concerns (DevEx teams and cluster providers and image-build tools).

But this conversation is the kick in the pants I probably needed to start some more formal conversations. I'll kick that off by filing some issues in this repo + the k3d repo + the microk8s repo and see where that goes.

**Comment by BenTheElder** [comment]
/override pull-kind-e2e-kubernetes
we're not changing kind sources here
