### PR TITLE
Copy scripts and configs separately during base image build

### LINKED ISSUE #2138: Copying files/ to / before clean-install, fails base image build
**What happened**:
```
$ make -C images/base quick
...<redacted>...
#7 0.150 Installing Packages ...
#7 0.231 Err:1 http://archive.ubuntu.com/ubuntu groovy InRelease
#7 0.231   Something wicked happened resolving 'archive.ubuntu.com:80' (-5 - No address associated with hostname)
#7 0.231 Err:2 http://archive.ubuntu.com/ubuntu groovy-updates InRelease
#7 0.231   Something wicked happened resolving 'archive.ubuntu.com:80' (-5 - No address associated with hostname)
#7 0.231 Err:3 http://security.ubuntu.com/ubuntu groovy-security InRelease
#7 0.231   Something wicked happened resolving 'security.ubuntu.com:80' (-5 - No address associated with hostname)
#7 0.232 Err:4 http://archive.ubuntu.com/ubuntu groovy-backports InRelease
#7 0.232   Something wicked happened resolving 'archive.ubuntu.com:80' (-5 - No address associated with hostname)
...<redacted>...
```

**What you expected to happen**:
base image is built successfully

**How to reproduce it (as minimally and precisely as possible)**:
This failed for me on my Google corp workstation, somehow works fine on Mac.

**Anything else we need to know?**:

This is most likely coming from us overwriting some of the `/etc` system files that we copy before running `clean-install`

https://github.com/kubernetes-sigs/kind/blob/426e03350adbe02b65cea8b4ddcfecd8b8119093/images/base/Dockerfile#L59

~wasn't able to pinpoint which one exactly, best guess is https://github.com/kubernetes-sigs/kind/blob/main/images/base/files/etc/sysctl.d/10-network-security.conf affecting the networking somehow?~

Some weird interaction with `/` being the destination ?

**Environment:**

- kind version: (use `kind version`): HEAD
- Kubernetes version: (use `kubectl version`): N/A
- Docker version: (use `docker info`): 20.10.2
- OS (e.g. from `/etc/os-release`):  Debian GNU/Linux

/cc @BenTheElder @aojea

### PR DESCRIPTION
**Pull request by amwat**
fixes #2138

Tested this fix locally and it works on my workstation now, and still works on Mac.

Not sure if we want to reorganize this in some other way to reduce layers

/cc @BenTheElder @aojea

### CODE REVIEW

File: images/base/Dockerfile [hunk 1]
```diff
@@ -95,8 +95,12 @@ RUN echo "Ensuring scripts are executable ..." \
...
       libseccomp2 pigz \
       bash ca-certificates curl rsync \
-      nfs-common \
-    && find /lib/systemd/system/sysinit.target.wants/ -name "systemd-tmpfiles-setup.service" -delete \
+      nfs-common
+
+# copy in static files (configs)
+COPY files/etc/ /etc/
+
+RUN echo "Cleanup temporary files ..." && find /lib/systemd/system/sysinit.target.wants/ -name "systemd-tmpfiles-setup.service" -delete \
```
Comment (BenTheElder) [inline images/base/Dockerfile:103]: this step cannot be separate, otherwise the deleted files are still in the layer below.

Comment (amwat) [reply images/base/Dockerfile:103]: Ack, I guess I can change on the next step instead cause we need the configs before enabling kubelet.

**Comment by aojea** [comment]
I can't see any other way to reduce layers than using ADD with a tarball or multistage, the squash flag is still "experimental"

**Comment by amwat** [comment]
updated to naively match 
https://github.com/kubernetes-sigs/kind/issues/2138#issuecomment-802367108

maybe we can reduce some of these?

File: images/base/Dockerfile [hunk 2]
```diff
@@ -88,8 +102,7 @@ COPY files/ /
 # This is plenty after we've done initial setup for a node, but before we are
 # likely to try to export logs etc.
 RUN echo "Ensuring scripts are executable ..." \
```
Comment (BenTheElder) [inline images/base/Dockerfile:104]: this log should be dropped

File: images/base/Dockerfile [hunk 3]
```diff
@@ -55,8 +55,22 @@ ARG CNI_PLUGINS_AMD64_SHA256SUM="962100bbc4baeaaa5748cdbfce941f756b1531c2eadb290
...
+COPY --chmod=0755 files/etc/systemd/system  /etc/systemd/
+COPY --chmod=0755 files/etc/systemd/system/kubelet.service.d  /etc/systemd/system/
+
+# all configs are 0644: http://www.filepermissions.com/file-permission/0644
+COPY --chmod=0644 files/etc/* /etc/
+COPY --chmod=0644 files/etc/containerd/* /etc/containerd/
+COPY --chmod=0644 files/etc/default/* /etc/default/
+COPY --chmod=0644 files/etc/sysctl.d/* /etc/sysctl.d/
+COPY --chmod=0644 files/etc/systemd/system/* /etc/systemd/system/
+COPY --chmod=0644 files/etc/systemd/system/kubelet.service.d/* /etc/systemd/system/kubelet.service.d/
```
Comment (BenTheElder) [inline images/base/Dockerfile:73]: this wound up really verbose.
maybe we should script creating a tarball in the makefile and then ADD it :/
at least then we could maybe programattically say "directories are X, files are Y, scripts are Z"

File: images/base/Dockerfile (hunk 2 above)
Comment (amwat) [reply images/base/Dockerfile]: done

File: images/base/Dockerfile (hunk 3 above)
Comment (aojea) [reply images/base/Dockerfile:68]: :)

Comment (BenTheElder) [reply images/base/Dockerfile:68]: there's some issues that approach too. discussed offline wtih amit, with correct usage of `COPY` (non recursive) directories will default to 755 like we want and it's not more verbose then.

**Comment by BenTheElder** [comment]
/lgtm
/hold
rebase this to HEAD, `make -C images/base push`, then bump the default.

File: images/base/Dockerfile (hunk 3 above)
Comment (aojea) [reply images/base/Dockerfile:68]: know I was wrong because I was assuming tar from a host, not from files in a git repo, but was surprisingly nice to see you reconsider it XD

**Comment by amwat** [comment]
done bumped to https://hub.docker.com/layers/kindest/base/v20210318-4009e6fd/images/sha256-f9026ddd33da088a9f81a41393189fc541485f8e1d4caad82a4d36ebfb3620d4?context=explore

File: pkg/build/nodeimage/defaults.go [hunk 4]
```diff
@@ -20,4 +20,4 @@ package nodeimage
 const DefaultImage = "kindest/node:latest"
 
 // DefaultBaseImage is the default base image used
-const DefaultBaseImage = "kindest/base:v20210315-64ac2e7f@sha256:d93111ce508dd3134141449d0658de71b6789c01ad73aa340c98b7e640e74ed8"
+const DefaultBaseImage = "kindest/base:v20210318-4009e6fd@sha256:f9026ddd33da088a9f81a41393189fc541485f8e1d4caad82a4d36ebfb3620d4"
```
Comment (BenTheElder) [inline pkg/build/nodeimage/defaults.go:23]: this should be sha256:c3c71ab9ad9c4f0e5fd8e3909854a4b8a3b7f50d39f3b814771d4e35f09a0e8f
```
crane digest kindest/base:v20210318-4009e6fd
sha256:c3c71ab9ad9c4f0e5fd8e3909854a4b8a3b7f50d39f3b814771d4e35f09a0e8f
```

the reason is multi-arch manifest digest vs the digest for just the amd64 image

Comment (amwat) [reply pkg/build/nodeimage/defaults.go]: done, this isn't visible on dockerhub anywhere?

Comment (BenTheElder) [reply pkg/build/nodeimage/defaults.go]: yeah, it isn't, someone at docker was going to try get that re-prioritized recently.

**Comment by aojea** [comment]
this was an impressive invetigation :muscle:
