### PR TITLE
Fix build node-image cmd and add user docs

### LINKED ISSUE #103: Build node-image using apt build type fails
Trying to build the `node-image` using the `apt` type fails:
```
INFO[15:00:54] Pulling image: k8s.gcr.io/kube-apiserver:v1.12.2 ... 
ERRO[15:00:55] Image build Failed! exit status 1            
FATA[15:00:56] Error building node image: exit status 1
```

The problems seems to be that during the build process, `kind` tries to save the required images to a temporary directory of the type `/tmp/kind-node-imageXXXXXXXXX/bits/images`:
https://github.com/kubernetes-sigs/kind/blob/6177a98223feedc7b8ab2e860b2311cb1f739acf/pkg/build/node/node.go#L368-L369

Extracting the output from the `docker.Save` command:
```
INFO[15:00:55] exit status 1                                
INFO[15:00:55] failed to save image: unable to validate output path: directory "/tmp/kind-node-image241009176/bits/images" does not exist
```

## Possible solution
During a previous step in the build process, build artifacts are moved to the temporary build directory by `populateBits`. This call will create the sub directory `bits` within the build directory `/tmp/kind-node-imageXXXXXXXX`.

https://github.com/kubernetes-sigs/kind/blob/6177a98223feedc7b8ab2e860b2311cb1f739acf/pkg/build/node/node.go#L150-L167

We could add another `exec.Command` here to create the `images` sub directory within `bits`.

Another possibility, would be to do this when the images are being pulled in (here we could more easily track where directories are being created)
https://github.com/kubernetes-sigs/kind/blob/6177a98223feedc7b8ab2e860b2311cb1f739acf/pkg/build/node/node.go#L359-L375

/kind bug

### PR DESCRIPTION
**Pull request by alejandrox1**
Resolves #103 
/kind bug
/kind documentation
    
Signed-off-by: Jorge Alarcon Ochoa <alarcj137@gmail.com>

### CODE REVIEW

File: cmd/kind/build/build.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ func NewCommand() *cobra.Command {
 		// TODO(bentheelder): more detailed usage
 		Use:   "build",
 		Short: "Build one of [base-image, node-image]",
-		Long:  "Build one of [base-image, node-image]",
+		Long:  "Build the base node image (base-image) or the node image (node-image)",
```
Comment (BenTheElder) [inline cmd/kind/build/build.go]: what does this look like at the CLI when printed? 
the short usage listing the valid options seems really handy, though obviously it would be great to also explain those options :-)

File: pkg/build/node/node.go [hunk 2]
```diff
@@ -355,6 +355,12 @@ func (c *BuildContext) prePullImages(dir, containerID string) error {
 		return err
 	}
 
+	// Create "images" subdir.
+	imagesDir := path.Join(dir, "bits", "images")
```
Comment (BenTheElder) [inline pkg/build/node/node.go]: at https://github.com/kubernetes-sigs/kind/pull/104/files#diff-7033e7fa5be88fc307b556fb3888ef42R374 we should use `pullTo := path.Join(imagesDir, image)` now that we have this value, so we can ensure they stay consistent.

File: pkg/build/node/node.go [hunk 3]
```diff
@@ -373,6 +379,12 @@ func (c *BuildContext) prePullImages(dir, containerID string) error {
 			movePulled = append(movePulled, fmt.Sprintf("/build/bits/images/%s", pullName))
 		}
 	}
+
+	// Create the /kind/images directory inside the container.
+	if err = execInBuild("mkdir", "-p", "/kind/images/"); err != nil {
```
Comment (BenTheElder) [inline pkg/build/node/node.go]: would you mind adding a TODO about pulling "/kind/images/" out to be in a constant?

File: docs/user-guide.md [hunk 4]
```diff
@@ -0,0 +1,51 @@
...
+## Building the base and node images
+### Base image
+`kind` runs a local kubernetes cluster by using Docker containers as "nodes."
+`kind` uses the [`node-image`][node image] to run kubernetes artifacts, such 
+as `kubeadm` or `kubelet`.
+The `node-image` in turn is built off the [`base-image`][base image], which
+installs all the dependencies needed for Docker and Kubernetes to run in a
+container.
+
+To build the `base-image` we use the `build` command:
```
Comment (BenTheElder) [inline docs/user-guide.md]: Users generally shouldn't need to build the base image, as we've published a pre-built one, we should probably detail this in a more advanced guide and focus on something like:

---
# User Guide
// what kind is
## Creating a Cluster
// how to create a generic cluster
// note about using a custom image
## Building Images
// how to build the node image, note about the base image existing

## Advanced
### Building The Base Image
// how to build the base image, how to use it with the node image
### Using Config
// how to use a config file and e.g. patch the kubeadm config

----

That way we can focus on the easy and most relevant parts first and progressively get into the weeds on implementation details and advanced usage. Most users don't need to worry too much about the base image, just know that it exists.

**Comment by BenTheElder** [comment]
Thanks so much for working on this! A couple of comments / questions. :smile: 
/ok-to-test

File: cmd/kind/build/build.go (hunk 1 above)
Comment (neolit123) [reply cmd/kind/build/build.go]: usually OK to omit long if short fits on a single line.

File: pkg/build/node/node.go [hunk 5]
```diff
@@ -355,6 +355,12 @@ func (c *BuildContext) prePullImages(dir, containerID string) error {
 		return err
 	}
 
+	// Create "images" subdir.
+	imagesDir := path.Join(dir, "bits", "images")
+	if err := os.Mkdir(imagesDir, 0777); err != nil {
```
Comment (BenTheElder) [inline pkg/build/node/node.go]: We should use `MkdirAll` here, which won't fail when the directory already exists (it will for the other build modes)
```suggestion
	if err := os.MkdirAll(imagesDir, 0777); err != nil {
```

File: cmd/kind/build/build.go (hunk 1 above)
Comment (alejandrox1) [reply cmd/kind/build/build.go]: kind-pr103
 What do you think?

File: pkg/build/node/node.go (hunk 2 above)
Comment (alejandrox1) [reply pkg/build/node/node.go]: Done

File: cmd/kind/build/build.go (hunk 1 above)
Comment (BenTheElder) [reply cmd/kind/build/build.go]: Looks good to me, thanks!

File: docs/README.md [hunk 6]
```diff
@@ -1,7 +1,9 @@
 # `kind` Documentation
 
-For the primary design start with [design.md]
+For the primary design start with [design][design].
 
-<!--TODO(bentheelder): add usage docs, link to some here and in the root README-->
+For usage documentation see the [user guide][user guide].
```
Comment (BenTheElder) [inline docs/README.md]: nit: let's put the shiny new user guide first :-)

**Comment by alejandrox1** [comment]
@BenTheElder made the changes. Tell me what you think?
Thank you very much for your comments :smile:

File: pkg/build/node/node.go [hunk 7]
```diff
@@ -365,15 +375,21 @@ func (c *BuildContext) prePullImages(dir, containerID string) error {
 			}
 			// TODO(bentheelder): generate a friendlier name
 			pullName := fmt.Sprintf("%d.tar", i)
-			pullTo := fmt.Sprintf("%s/bits/images/%s", dir, pullName)
+			pullTo := fmt.Sprintf("%s/%s", imagesDir, pullName)
```
Comment (BenTheElder) [inline pkg/build/node/node.go]: we should use `path.Join` because this is on the host so the separator may not be `/`, whereas the paths "on the node" will be linux paths. (in practice this code should generally be fine, but we should be consistent anyhow)
```suggestion
			pullTo := path.Join(imagesDir, pullName)
```

**Comment by alejandrox1** [comment]
So, I moved the link to the user guide to the top of the README in the docs. Is that good enoguh for now or are there any other changes you'd like to see?

**Comment by alejandrox1** [comment]
@BenTheElder , placed the ref to the user guide befor the design docs and linked to it from the README.
Tell me if that looks alright

File: docs/user-guide.md (hunk 4 above)
Comment (BenTheElder) [reply docs/user-guide.md]: actually I'll rearrange a bit in a follow up
